### ISSUE TITLE
Inline Options Feasibility

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/gulp-recess#13]
With tools like jshint, we're able to define configuration options for a file as an inline comment at the top of the file (and throughout code for blocks). I haven't been able to find any mention of an option like this for recess as yet, but something like that on the file-level would be immensely helpful.

I have a working example for how to integrate that with gulp-recess, per file, but before submitting a PR on it, I was wondering if the maintainers of gulp-recess think it'd be feasible to integrate into gulp-recess. The recess project is notoriously difficult to get work reviewed and merged, and this would be a quick win and value-add for gulp-recess separately.

**Comment by sindresorhus** [comment]
You would have to ask on https://github.com/twitter/recess/issues which is the underlying lib.

**Comment by shellscape** [comment]
I did already address going to recess. The last approved addition to recess:master was in 2013, and the last addition to the 2.0 branch was 7 months ago! When an underlying project stops responding and has poor maintenance, it's common practice to extend the tooling around it.

I really wish you hadn't closed this without some more discussion, but fair enough. We'll likely fork gulp-recess as a new module rather than try and deal with the recess project.

**Comment by sindresorhus** [comment]
@shellscape Yeah, that is indeed unfortunate. I would be happy to switch to depend on an actively maintained fork (for my grunt-recess plugin too) of RECESS (hint hint), but putting that kind of logic in a gulp plugin is not the way to do it.

**Comment by sindresorhus** [comment]
Seems like you ignored my recommendation...

https://github.com/shellscape/gulp-recess-plus
