### ISSUE TITLE
Project based on Twitter Bootstrap, errors

### ISSUE THREAD

**Issue by mnowakowski** [sindresorhus/gulp-recess#14]
Hi!
I have project based on Twitter Bootstrap ver. 3.1.1. At this moment I've got a lot of errors and *recess* not work properly. One example:
```
columnNumber: 25,
  fileName: 'bower_components/bootstrap/less/mixins.less',
  lineNumber: 643,
  type: undefined,
  name: 'Error',
  message: 'Syntax Error on line 643',
  stack: undefined,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-recess',
  __safety: { toString: [Function] },
  recess:
   { message: 'Syntax Error on line 643',
     filename: 'bower_components/bootstrap/less/mixins.less',
     line: 643,
     col: 25 } }
```
Line 643 in 'bower_components/bootstrap/less/mixins.less':
```
&:extend(.clearfix all);
```

Is it possible that the gulp-recess work properly on Bootsrap structure? If 'NO', is it mean that I have to switch to Grunt?

Regards!
M.

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the RECESS [issue tracker](https://github.com/twitter/recess/issues).*
