### ISSUE TITLE
events.js:141 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Teenie-weenie** [sindresorhus/gulp-recess#16]
I don't know, maybe I do something wrong, but when I try to use `gulp-recess`, it doesn't work.  
This is my **gulpfile.js** file

    
    'use strict';

    var gulp = require('gulp'),
	    recess = require('gulp-recess');
	
	gulp.task('default', function () {
    return gulp.src('css/style.css')
        .pipe(recess())
        .pipe(recess.reporter())
        .pipe(gulp.dest('dist'));
    }); 

And I try to use it with simple css file like
    
    body {
	    color: red;
	    font-size: 40px;
	    background: green;
    }

I've got error in Node.js console  
 
[![http://i.imgur.com/WOTgMcS.png][1]][1]

Am I doing something wrong?

  [1]: http://i.imgur.com/WOTgMcS.png

**Comment by sindresorhus** [comment]
Read the output. It's all there. You have `Busted 1 failures`. That's why you have the `Unhandled error event`. The whole point of this module it to enforce a certain style.

**Comment by Teenie-weenie** [comment]
I'm sorry but I don't understand what's wrong with my css style. Could you explain me please?

**Comment by sindresorhus** [comment]
It says so right in the output. You have an incorrect property order for your CSS, according to the RECESS rules.
