### ISSUE TITLE
Error output not displayed in VS2015 Task Runner

### ISSUE THREAD

**Issue by daggmano** [sindresorhus/gulp-recess#17]
Not sure if this is a gulp-recess issue or a VS2015 task runner issue.  When an error is found in a LESS file, the recess-reporter is correctly halting progress, but no output is displayed:

    [22:19:21] Processing LESS files
      [gulp-recess] site.less: Busted 2 failures
    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: site.less: Busted 2 failures
    Process terminated with code 8.

Kind of makes things hard to fix with no output.  Anybody know if there is a workaround?

**Comment by leniency** [comment]
My quick workaround was just to manually catch and display the error. Basically just this:

    .pipe(recess())           // Lint
    .on('error', function (error) {
        util.log(error);  // gulp-util module to log.
    })
